fun main(args: Array<String>) {
    println("Hello World!")

    var x = 17

    var obj1 = MyQueue()
    obj1.push(x)
    obj1.push(x + 13)
    var p2 = obj1.pop()
    var p3 = obj1.peek()
    var p4 = obj1.empty()
    println(p2)
    println(p3)
    println(p4)
    obj1.push(x + 132)
    p2 = obj1.pop()
    p3 = obj1.peek()
    p4 = obj1.empty()
    println(p2)
    println(p3)
    println(p4)
    obj1.push(x - 1)
    p2 = obj1.pop()
    p3 = obj1.peek()
    p4 = obj1.empty()
    println(p2)
    println(p3)
    println(p4)

    var obj2 = MyStack()
    obj2.push(x)
    var pa2 = obj2.pop()
    println(pa2)
    var pa3 = obj2.top()
    println(pa3)
    var pa4 = obj2.empty()
    println(pa4)
    var pa5 = obj2.pop()
    println(pa5)
}